#!/bin/sh

# Copyright © 2019 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u
[ $# = 2 ] || {
    printf 'Usage: %s TIME1 TIME2\n' "${0##*/}" >&2
    exit 1
}
[ $(id -u) -eq 0 ] || exec sudo "$0" "$@"
dev=/sys/devices/platform/i8042/serio0/input/input0/input0::scrolllock
while true
do
    echo 0 > "$dev/brightness"
    sleep "$1"
    echo 1 > "$dev/brightness"
    timeout --foreground "$2" sh -c 'read x' ||
        poweroff
done

# vim:ts=4 sts=4 sw=4 et
